---
deployment:
  tasks:
    - export DEPLOYPATH=/home/siakads4/public_html/
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R core $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH/public/uploads
